<div class="footer-bg">
    <div class="footer-wrap">
        <div class="footer-acorn"></div>
        <div class="footer flow">
            <div class="footer-inner">
                <div class="footer-list-wrap">
                    <ul class="main-footer-menu">
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#synopsis">Synopsis</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#clips">Clips</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#cast">Cast</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#screenings">Screenings</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#blog">Evan's Blog</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#bonus">Bonus Material</a></li>
                        <li><a href="http://shop.letterstotheexiles.com">Shop</a></li>
                        <li><a href="http://www.letterstotheexiles.com/flow-page/#contact">Contact Us</a></li>
                    </ul>
                </div>
                <div class="copyright text-center">
                    <p>&copy; <?php echo date('Y'); ?> Acton Institute. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</div> <!-- /footer -->