<?php
/**
 * @category    design
 * @package     vilepickle_letterstotheexiles
 * @copyright   2013 David Lohmeyer
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
<?php echo $this->getChildHtml('head') ?>
<script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

<div id="pagebackground">
        <?php echo $this->getChildHtml('header') ?>
        <div class="body-area brown-area">
            <div class="container">
                <div id="main" class="row">
                    <div id="content" class="bodytext">
                        <div class="col-md-3 sidebar-column">
                            <?php echo $this->getChildHtml('left') ?>
                        </div>
                        <div class="col-md-6">
                            <div id="content-inner" class="inner column center">
                                <?php echo $this->getChildHtml('breadcrumbs') ?>
                                <div id="content-area">
                                    <?php echo $this->getChildHtml('global_notices') ?>
                                    <?php echo $this->getChildHtml('global_messages') ?>
                                    <?php echo $this->getChildHtml('store_language') ?>
                                    <p class="welcome-msg"><?php echo $this->getWelcome()?></p>
                                    <?php echo $this->getChildHtml('content') ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 sidebar-column">
                            <?php echo $this->getChildHtml('right') ?>
                        </div>
                    </div> <!-- /content-inner /content -->
              </div><!-- /main -->
            </div><!--/.container-->
        </div>
</div><!--/#pagebackground-->
<div class="hole stream-hole">
    <img src="<?php echo $this->getSkinUrl('images/ltte/stream-flow.jpg'); ?>"/>
</div>

<div class="stream-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content-block-inner">
                    <div class="block-inner">
                        <div class="stream-wrapper flow-content-block">
                            <div class="stream-header text-center">
                                <div class="row">

                                </div>
                                <div class="row">
                                    <div class="stream-block col-xs-6 col-sm-6 col-md-2 col-md-push-1 text-center">
                                        <a href="http://www.letterstotheexiles.com/watch-yekra/"><img alt="Available for streaming on Yekra" class="img-responsive" src="<?php echo $this->getSkinUrl('images/ltte/stream_yekra.jpg'); ?>"/></a>
                                    </div>
                                    <div class="stream-block col-xs-6 col-sm-6 col-md-2 col-md-push-1 text-center">
                                        <a href="https://flannel.org/store/films/flow" target="_blank"><img alt="Available for streaming on Flannel.org" class="img-responsive" src="<?php echo $this->getSkinUrl('images/ltte/stream_flannel.jpg'); ?>"/></a>
                                    </div>
                                    <div class="stream-block col-xs-6 col-sm-6 col-md-2 col-md-push-1 text-center">
                                        <a href="http://www.google.com/tv/" target="_blank"><img alt="Available on GoogleTV" class="img-responsive" src="<?php echo $this->getSkinUrl('images/ltte/stream_google.jpg'); ?>"/></a>
                                    </div>
                                    <div class="stream-block col-xs-6 col-sm-6 col-md-2 col-md-push-1 text-center">
                                        <a href="http://www.roku.com/channels/#!details/43207/for-the-life-of-the-world" target="_blank"><img alt="Available on Roku" class="img-responsive" src="<?php echo $this->getSkinUrl('images/ltte/stream_roku.jpg'); ?>"/></a>
                                    </div>
                                    <div class="stream-block col-xs-12 col-sm-12 col-md-2 col-md-push-1 text-center">
                                        <a href="http://www.studyspace.org/" target="_blank"><img alt="Available at Studyspace.org" class="img-responsive" src="<?php echo $this->getSkinUrl('images/ltte/stream_studyspace.jpg'); ?>"/></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="contact-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="content-block-inner">
                    <div class="block-inner">
                        <div class="block-title-wrap">
                            <div class="block-title-inner">
                                <h3>Contact us</h3>
                            </div>
                        </div>
                        <div class="contact-wrapper flow-content-block">
                            <div class="contact-header">
                                <p>Need a little help figuring out how to engage with For the life of the World? We are glad you asked.</p>

                                <p>Whether you're a home group leader, a church or organization leader, or just plain you, we would love to help!</p>
                                <p>Use the email bellow to connect with the right person.</p>
                                <ul>
                                    <li>
                                        <p>product inquiries:</p>
                                        <a href="mailto:products@letterstotheexiles.com?subject=FLOW Product Inquiry">products@letterstotheexiles.com</a>
                                    </li>
                                    <li>
                                        <p>shop order inquiries:</p>
                                        <a href="mailto:shop@letterstotheexiles.com?subject=FLOW Order Inquiry">shop@letterstotheexiles.com</a>
                                    </li>
                                    <li>
                                        <p>event booking inquiries:</p>
                                        <a href="mailto:events@letterstotheexiles.com?subject=FLOW Event Booking Inquiry">events@letterstotheexiles.com</a>
                                    </li>
                                    <li>
                                        <p>current screenings:</p>
                                        <a href="mailto:screenings@letterstotheexiles.com?subject=FLOW Screenings Inquiry">screenings@letterstotheexiles.com</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="hole">
    <img src="<?php echo $this->getSkinUrl('images/ltte/telephone.jpg'); ?>"/>
</div>

<div class="contact-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="home-social-wrap">
                    <p class="social-title">Follow us</p>
                    <ul class="social-media">
                        <li class="fb">
                            <a target="_blank" href="https://www.facebook.com/LettersToTheExiles">facebook</a>
                        </li>
                        <li class="tw">
                            <a target="_blank" href="https://twitter.com/letterstoexiles">twitter</a>
                        </li>
                        <li class="google">
                            <a target="_blank" href="https://plus.google.com/u/0/b/106421644184098494799/">google plus</a>
                        </li>
                        <li class="instagram">
                            <a target="_blank" href="http://instagram.com/instaexile">instagram</a>
                        </li>
                        <li class="yt">
                            <a target="_blank" href="https://www.youtube.com/user/LettersToTheExiles">youtube</a>
                        </li>
                        <li class="rss">
                            <a href="http://www.letterstotheexiles.com/feed/" target="_blank">rss</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1853121-1', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript">
  var _sf_async_config = { uid: 57713, domain: 'acton.org', useCanonical: true };
      (function() {
          function loadChartbeat() {
              window._sf_endpt = (new Date()).getTime();
              var e = document.createElement('script');
              e.setAttribute('language', 'javascript');
              e.setAttribute('type', 'text/javascript');
              e.setAttribute('src','//static.chartbeat.com/js/chartbeat.js');
              document.body.appendChild(e);
          };
          var oldonload = window.onload;
          window.onload = (typeof window.onload != 'function') ?
          loadChartbeat : function() { oldonload(); loadChartbeat(); };
       })();
</script>

</body>
</html>
